// API client for "Transacción Reactiva con Spring WebFlux y React Native" (generated by gherkin-ai).
// Contract: POST /api/v1/transaccion-reactiva-con-spring-web-flux-y-react-native/{id}/{command} -> 201 { type, aggregateId, version }

export const COMMANDS = ['process_transaccion_reactiva_con_spring_web_flux_y_react_native'] as const;
export type CommandName = (typeof COMMANDS)[number];

export interface CommandResult {
  type: string;
  aggregateId: string;
  version: number;
}

export class ApiError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message);
    this.name = 'ApiError';
  }
}

export interface ClientOptions {
  /** Backend origin, e.g. https://api.example.com (default: same origin). */
  baseUrl?: string;
  tenantId?: string;
  fetch?: typeof fetch;
  /**
   * W3C trace context sent as the traceparent header, so the backend's spans join the caller's trace.
   * Default: a new sampled root context per request. Pass a function to propagate an existing trace
   * (e.g. from @opentelemetry/api), or false to send none.
   */
  traceparent?: false | (() => string | undefined);
}

export interface ExecuteOptions {
  /** Sent as X-Idempotency-Key so retries are safe. */
  idempotencyKey?: string;
}

const hex = (bytes: number) => {
  const values = new Uint8Array(bytes);
  if (globalThis.crypto?.getRandomValues) globalThis.crypto.getRandomValues(values);
  else for (let i = 0; i < bytes; i++) values[i] = Math.floor(Math.random() * 256);
  return Array.from(values, v => v.toString(16).padStart(2, '0')).join('');
};

/** A new sampled W3C traceparent (version 00) for a request that starts a trace. */
export function newTraceparent(): string {
  return `00-${hex(16)}-${hex(8)}-01`;
}

export function createTransaccionReactivaConSpringWebFluxYReactNativeClient(options: ClientOptions = {}) {
  const baseUrl = (options.baseUrl ?? '').replace(/\/$/, '');
  const doFetch = options.fetch ?? ((...args: Parameters<typeof fetch>) => fetch(...args));

  async function execute(id: string, command: CommandName, payload: Record<string, unknown> = {}, opts: ExecuteOptions = {}): Promise<CommandResult> {
    const headers: Record<string, string> = { 'Content-Type': 'application/json', Accept: 'application/json' };
    if (options.tenantId) headers['X-Tenant-Id'] = options.tenantId;
    if (opts.idempotencyKey) headers['X-Idempotency-Key'] = opts.idempotencyKey;
    const traceparent = options.traceparent === false ? undefined : (options.traceparent ?? newTraceparent)();
    if (traceparent) headers.traceparent = traceparent;

    const res = await doFetch(`${baseUrl}/api/v1/transaccion-reactiva-con-spring-web-flux-y-react-native/${encodeURIComponent(id)}/${command}`, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload)
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) throw new ApiError(res.status, (body as { detail?: string }).detail ?? `Request failed with status ${res.status}`);
    return body as CommandResult;
  }

  return {
    execute,
    processTransaccionReactivaConSpringWebFluxYReactNative: (id: string, payload?: Record<string, unknown>, opts?: ExecuteOptions) => execute(id, 'process_transaccion_reactiva_con_spring_web_flux_y_react_native', payload, opts),
  };
}

export type TransaccionReactivaConSpringWebFluxYReactNativeClient = ReturnType<typeof createTransaccionReactivaConSpringWebFluxYReactNativeClient>;
