package com.example.transactionalsystemjavareactnative.domain;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Domain kernel for "Transacción Reactiva con Spring WebFlux y React Native" (generated by gherkin-ai).
 * Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.
 */
public class TransaccionReactivaConSpringWebFluxYReactNativeAggregate {
    private final String id;
    private TransaccionReactivaConSpringWebFluxYReactNativeState state = TransaccionReactivaConSpringWebFluxYReactNativeState.PENDING;
    private long version;
    private final List<TransaccionReactivaConSpringWebFluxYReactNativeDomainEvent> pendingEvents = new ArrayList<>();

    public TransaccionReactivaConSpringWebFluxYReactNativeAggregate(String id) {
        if (id == null || id.isBlank()) throw new DomainValidationException("TransaccionReactivaConSpringWebFluxYReactNative id is required");
        this.id = id;
    }

    /** Rebuilds an aggregate from persisted state; no events are recorded. */
    public static TransaccionReactivaConSpringWebFluxYReactNativeAggregate restore(String id, TransaccionReactivaConSpringWebFluxYReactNativeState state, long version) {
        var aggregate = new TransaccionReactivaConSpringWebFluxYReactNativeAggregate(id);
        aggregate.state = state;
        aggregate.version = version;
        return aggregate;
    }

    public String getId() { return id; }
    public TransaccionReactivaConSpringWebFluxYReactNativeState getState() { return state; }
    public long getVersion() { return version; }

    /** Events recorded since the aggregate was loaded (to be saved via the outbox). */
    public List<TransaccionReactivaConSpringWebFluxYReactNativeDomainEvent> getPendingEvents() { return Collections.unmodifiableList(pendingEvents); }

    public TransaccionReactivaConSpringWebFluxYReactNativeDomainEvent processTransaccionReactivaConSpringWebFluxYReactNative(TransaccionReactivaConSpringWebFluxYReactNativeCommand command) {
        assertValid(command);
        return record(TransaccionReactivaConSpringWebFluxYReactNativeEventType.EmiteFlujoServerSentEventFluxConsumidoPorUseQueryEnReactNati, command.payload());
    }

    private void assertValid(TransaccionReactivaConSpringWebFluxYReactNativeCommand command) {
        if (command == null || command.id() == null || command.id().isBlank()) throw new DomainValidationException("Command id is required");
        if (!command.id().equals(id)) throw new DomainValidationException("Command targets " + command.id() + ", not " + id);
    }

    private TransaccionReactivaConSpringWebFluxYReactNativeDomainEvent record(TransaccionReactivaConSpringWebFluxYReactNativeEventType type, Map<String, Object> payload) {
        version += 1;
        var event = new TransaccionReactivaConSpringWebFluxYReactNativeDomainEvent(type, id, version, Instant.now(), payload == null ? Map.of() : payload);
        pendingEvents.add(event);
        return event;
    }
}
