package com.example.transactionalsystemjavareactnative.domain;

public enum TransaccionReactivaConSpringWebFluxYReactNativeEventType {
    EmiteFlujoServerSentEventFluxConsumidoPorUseQueryEnReactNati,
    TransaccionReactivaConSpringWebFluxYReactNativeProcessed
}
